### ISSUE TITLE
32u4 not appearing in Windows Drivers

### ISSUE THREAD

**Issue by Minimal88** [adafruit/Adafruit_Windows_Drivers#11]
Option for installing the 32u4 is not appearing my windows 10 laptop. And when trying to upload sketch (from Arduino IDE) appears a error message saying that programmer is not responding
![image](https://user-images.githubusercontent.com/16052713/44066514-f26706ca-9f2d-11e8-9d0b-1f6ed3da01ea.png)

![image](https://user-images.githubusercontent.com/16052713/44066690-e5421df8-9f2e-11e8-9bfd-5f3eb132d354.png)

**Comment by dhalbert** [comment]
Windows 10 does not need a third-party driver, so we have suppressed the listing when you run the installer on Windows 10. The board should show up as a usbser.sys USB serial device in Device Manager. Check out the trouble-shooting tips here: https://learn.adafruit.com/adafruit-feather-32u4-basic-proto/feather-help.

If you need further help please ask in https://forums.adafruit.com, as this is a support issue, rather than a bug. Thanks!
